AllCops:
  TargetRubyVersion: 3.2
  # temporary disable
  NewCops: disable

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false

# Allow safe assignment in conditions.
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true
