AllCops:
  TargetRubyVersion: 3.1
  # temporary disable
  NewCops: disable

Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/MissingSuper:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

# Allow safe assignment in conditions.
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true
